neptune:
    routing:
        root_url: track-stuff.dev/
    database:
        main:
            driver: pdo_mysql
            dbname: track_stuff
            user: root
            pass: ''
            logger: logger
